/* The following code was generated by JFlex 1.7.0 tweaked for IntelliJ platform */

package com.outskirtslabs.beancount.parser;

import java.util.LinkedList;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;

import static com.intellij.psi.TokenType.BAD_CHARACTER;
import static com.intellij.psi.TokenType.WHITE_SPACE;
import static com.outskirtslabs.beancount.psi.BeancountTypes.*;
import static com.outskirtslabs.beancount.BeancountLexerUtil.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Beancount.flex</tt>
 */
public class _BeancountLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int sOPT = 2;
  public static final int sEVENT = 4;
  public static final int sDATE_ENTRY = 6;
  public static final int sOPEN = 8;
  public static final int sBALANCE = 10;
  public static final int sPRICE = 12;
  public static final int sCOMMODITY = 14;
  public static final int sMETA_LIST = 16;
  public static final int sPOSTING = 18;
  public static final int sACCOUNT = 20;
  public static final int sTXN = 22;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  1,  2,  3,  2,  3,  4,  5,  6,  7,  6,  7,  2,  3,  2,  3, 
     8,  9, 10, 11, 12, 13, 14, 15
  };

  /** 
   * Translates characters to character classes
   * Chosen bits are [11, 6, 4]
   * Total runtime size is 8128 bytes
   */
  public static int ZZ_CMAP(int ch) {
    return ZZ_CMAP_A[(ZZ_CMAP_Y[(ZZ_CMAP_Z[ch>>10]<<6)|((ch>>4)&0x3f)]<<4)|(ch&0xf)];
  }

  /* The ZZ_CMAP_Z table has 1088 entries */
  static final char ZZ_CMAP_Z[] = zzUnpackCMap(
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\12\1\13\35\12\1\14\1\15\24\12"+
    "\1\16\1\12\1\17\1\12\1\20\1\21\1\22\1\23\1\24\22\12\1\25\32\12\1\26\4\12\1"+
    "\27\1\12\1\30\u03c3\12");

  /* The ZZ_CMAP_Y table has 1600 entries */
  static final char ZZ_CMAP_Y[] = zzUnpackCMap(
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7\1\10\3\1\1\11\1\12\2\1\3\13\1\14\1\15\2\13"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\13\1\25\3\13\1\26\1\27\22\1\1\30\1\31"+
    "\1\32\1\33\1\1\1\34\1\35\1\13\1\36\3\11\3\1\2\13\1\37\3\13\1\40\6\13\1\32"+
    "\1\11\1\41\20\1\1\42\10\1\1\42\14\1\1\42\31\1\1\43\7\1\1\43\7\1\1\43\7\1\1"+
    "\43\7\1\1\43\7\1\1\43\7\1\1\43\7\1\1\43\7\1\1\43\7\1\1\43\6\1\1\42\7\1\1\42"+
    "\4\1\1\42\21\1\1\42\4\1\1\42\2\11\1\44\55\1\5\11\1\45\76\1\1\42\2\1\1\42\22"+
    "\1\1\43\10\1\1\42\12\1\2\42\13\1\1\42\5\1\1\42\10\1\2\42\32\1\11\13\1\46\6"+
    "\13\1\47\1\50\2\47\1\50\1\51\1\47\4\1\3\52\1\53\1\52\2\1\1\54\15\1\1\55\1"+
    "\56\1\57\1\60\1\61\1\1\1\11\1\1\1\62\62\1\1\63\1\11\163\1\2\11\1\64\3\1\1"+
    "\65\1\66\6\13\1\67\1\70\122\1\1\42\1\1\2\13\1\71\1\1\1\13\1\72\10\1\2\73\3"+
    "\13\1\74\1\75\1\76\1\77\1\100\21\1\1\42\2\1\1\42\14\1\1\42\1\1\1\42\5\1\1"+
    "\42\31\1\1\42\61\1\1\42\1\32\1\101\14\1\2\11\1\102\7\1\1\42\2\11\1\103\72"+
    "\1\3\11\1\104\72\1\1\43\10\1\1\42\3\1\1\43\11\1\1\42\21\1\1\42\25\1\1\42\7"+
    "\1\1\42\27\1\1\42\6\1\1\42\6\1\1\42\26\1\2\11\2\1\1\42\66\1\1\42\140\1\1\42"+
    "\16\1\1\42\12\1\1\11\1\105\1\1\1\106\1\107\1\1\1\47\1\11\1\110\1\111\1\112"+
    "\1\45\1\1\1\11\1\105\1\1\1\113\1\114\1\1\1\115\1\116\1\117\1\120\1\11\1\45"+
    "\1\1\1\11\1\105\1\1\1\106\1\107\1\1\1\47\1\11\1\110\1\120\1\11\1\45\1\1\1"+
    "\11\1\105\1\1\1\47\1\11\1\117\1\1\1\121\1\101\1\1\1\120\1\11\1\122\1\1\1\63"+
    "\1\64\2\1\1\11\1\123\1\1\1\124\3\125\20\1\2\11\1\110\2\1\1\42\75\1\1\11\1"+
    "\105\1\11\1\105\1\11\1\105\47\1");

  /* The ZZ_CMAP_A table has 1376 entries */
  static final char ZZ_CMAP_A[] = zzUnpackCMap(
    "\12\0\1\7\2\10\1\7\22\0\1\12\1\13\1\5\1\23\4\0\1\50\1\51\1\53\1\52\1\47\1"+
    "\3\1\2\1\20\12\1\1\22\1\11\4\0\1\21\32\16\1\0\1\6\1\0\1\24\1\17\1\0\1\35\1"+
    "\34\1\30\1\40\1\31\3\15\1\27\2\15\1\36\1\37\1\33\1\32\1\25\1\15\1\26\1\15"+
    "\1\41\1\15\1\43\1\15\1\44\1\42\1\15\1\45\1\0\1\46\7\0\1\10\12\0\27\14\1\0"+
    "\7\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1"+
    "\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\2\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14"+
    "\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\2\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\1"+
    "\0\1\14\1\0\1\14\1\0\1\14\1\0\2\14\1\0\1\14\1\0\1\14\3\0\2\14\1\0\1\14\1\0"+
    "\2\14\1\0\3\14\2\0\4\14\1\0\2\14\1\0\3\14\3\0\2\14\1\0\2\14\1\0\1\14\1\0\1"+
    "\14\1\0\2\14\1\0\1\14\2\0\1\14\1\0\2\14\1\0\3\14\1\0\1\14\1\0\2\14\3\0\1\14"+
    "\7\0\1\14\2\0\1\14\2\0\1\14\2\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\1"+
    "\0\1\14\1\0\1\14\1\0\1\14\2\0\1\14\2\0\1\14\2\0\1\14\1\0\3\14\1\0\1\14\1\0"+
    "\1\14\1\0\1\14\1\0\1\14\1\0\1\14\7\0\2\14\1\0\2\14\2\0\1\14\1\0\4\14\1\0\1"+
    "\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\3\0\1\14\10\0\1\14\6\0\1"+
    "\14\1\0\3\14\1\0\1\14\1\0\2\14\1\0\21\14\1\0\11\14\23\0\1\14\2\0\3\14\3\0"+
    "\1\14\1\0\1\14\1\0\1\14\1\0\1\14\5\0\1\14\2\0\1\14\1\0\2\14\2\0\4\14\11\0"+
    "\1\14\1\0\1\14\1\0\1\14\1\0\2\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1"+
    "\14\1\0\1\14\2\0\7\14\11\0\12\4\14\0\12\4\6\14\1\0\1\14\5\0\1\14\2\0\6\14"+
    "\12\0\1\14\1\0\1\14\1\0\1\14\11\0\1\14\11\0\10\14\10\0\6\14\13\0\1\14\1\0"+
    "\1\14\1\0\1\14\1\0\1\14\10\0\4\14\14\0\5\14\13\0\2\10\10\0\1\14\4\0\1\14\3"+
    "\0\3\14\2\0\3\14\2\0\1\14\3\0\5\14\6\0\1\14\1\0\1\14\1\0\1\14\1\0\4\14\2\0"+
    "\4\14\12\0\2\14\5\0\1\14\15\0\1\14\22\0\31\14\1\0\1\14\1\0\3\14\2\0\1\14\1"+
    "\0\1\14\1\0\1\14\1\0\4\14\1\0\1\14\2\0\1\14\10\0\3\14\1\0\1\14\10\0\1\14\1"+
    "\0\1\14\4\0\1\14\15\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\1"+
    "\0\1\14\3\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\7\0\1\14\1\0"+
    "\1\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\12\0\1\14\1\0\1\14\1\0"+
    "\2\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\4\0\1\14\1\0\1\14\2\0\1\14\1\0\1"+
    "\14\3\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14\1\0\1\14"+
    "\1\0\1\14\1\0\1\14\1\0\5\14\1\0\5\14\1\0\1\14\11\0\13\14\5\0\10\14\10\0\4"+
    "\14\14\0\3\14\15\0\12\14\12\0\32\14\2\0\2\14\32\0\1\14\1\0\2\14\2\0\1\14\2"+
    "\0\2\14\2\0\4\14\1\0\2\14\4\0\2\14\1\0\4\14\2\0\10\14\1\0\7\14\13\0\2\14\1"+
    "\0\4\14\1\0\5\14\1\0\1\14\3\0\7\14\33\0\4\14\2\0\23\14\13\0\11\14\21\0\1\14"+
    "\3\0\22\4");

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\20\0\1\1\1\2\1\3\2\1\1\4\1\5\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\2\3\1\3\20\1\21\1\22\1\20"+
    "\1\22\1\23\6\20\2\24\1\25\1\20\1\26\1\27"+
    "\1\30\1\31\1\32\1\30\1\33\1\34\1\33\1\4"+
    "\1\35\1\22\2\2\1\0\1\36\1\0\1\37\2\0"+
    "\1\40\1\41\1\42\1\43\1\2\12\0\1\40\1\44"+
    "\1\45\1\46\1\2\1\0\1\36\1\2\1\0\1\47"+
    "\6\0\1\2\1\0\1\2\5\0\1\50\1\0\1\2"+
    "\3\0\1\51\1\0\1\52\3\0\1\53\5\0\1\54"+
    "\5\0\1\55\1\56\1\57";

  private static int [] zzUnpackAction() {
    int [] result = new int[142];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\260\0\334\0\u0108\0\u0134"+
    "\0\u0160\0\u018c\0\u01b8\0\u01e4\0\u0210\0\u023c\0\u0268\0\u0294"+
    "\0\u02c0\0\u02ec\0\u0318\0\u0344\0\u0370\0\u039c\0\u03c8\0\u03f4"+
    "\0\u02c0\0\u0420\0\u02c0\0\u044c\0\u0478\0\u02c0\0\u02c0\0\u02c0"+
    "\0\u02c0\0\u02c0\0\u04a4\0\u04d0\0\u04fc\0\u0528\0\u02c0\0\u0344"+
    "\0\u0370\0\u0554\0\u0580\0\u03f4\0\u05ac\0\u02c0\0\u05d8\0\u0604"+
    "\0\u0630\0\u065c\0\u0688\0\u06b4\0\u06e0\0\u070c\0\u0738\0\u0764"+
    "\0\u02c0\0\u02c0\0\u0790\0\u07bc\0\u02c0\0\u07e8\0\u02c0\0\u0814"+
    "\0\u0370\0\u0840\0\u02c0\0\u086c\0\u0898\0\u08c4\0\u08f0\0\u091c"+
    "\0\u0370\0\u02c0\0\u0948\0\u03f4\0\u03f4\0\u02c0\0\u02c0\0\u02c0"+
    "\0\u0974\0\u09a0\0\u04fc\0\u09cc\0\u09f8\0\u0a24\0\u0a50\0\u0a7c"+
    "\0\u0aa8\0\u0ad4\0\u0b00\0\u070c\0\u0764\0\u0840\0\u0b2c\0\u0b58"+
    "\0\u0b84\0\u0bb0\0\u0bdc\0\u0c08\0\u09cc\0\u0c34\0\u0c60\0\u0c8c"+
    "\0\u0cb8\0\u0ce4\0\u0d10\0\u0d3c\0\u0d68\0\u0d94\0\u0dc0\0\u0dec"+
    "\0\u0e18\0\u0e44\0\u0e70\0\u02c0\0\u0e9c\0\u0ec8\0\u0ef4\0\u0f20"+
    "\0\u0f4c\0\u02c0\0\u0f78\0\u02c0\0\u0fa4\0\u0fd0\0\u0ffc\0\u02c0"+
    "\0\u1028\0\u1054\0\u1080\0\u10ac\0\u10d8\0\u02c0\0\u1104\0\u1130"+
    "\0\u115c\0\u1188\0\u11b4\0\u02c0\0\u02c0\0\u02c0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[142];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\21\1\22\1\21\1\23\1\24\1\25\1\21\1\26"+
    "\1\21\1\27\4\21\1\30\1\21\1\31\1\32\1\21"+
    "\1\33\21\21\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\21\1\43\1\21\1\23\1\44\1\25\1\21"+
    "\1\26\1\21\1\27\1\45\3\21\1\30\1\21\1\31"+
    "\1\32\1\21\1\33\6\21\1\46\12\21\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\47\1\22\1\47"+
    "\1\23\1\50\1\51\1\47\1\52\2\47\1\53\3\47"+
    "\1\54\1\47\1\31\1\32\1\47\1\33\21\47\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\47\1\22"+
    "\1\47\1\23\1\50\1\51\1\47\1\52\2\47\1\55"+
    "\3\47\1\54\1\47\1\31\1\32\1\47\1\33\21\47"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\47"+
    "\1\22\1\47\1\23\1\50\1\51\4\47\1\53\1\56"+
    "\2\47\1\54\1\47\1\31\1\32\1\47\1\33\1\47"+
    "\1\57\2\47\1\60\1\61\1\62\1\47\1\63\4\47"+
    "\1\64\3\47\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\56\1\47\1\22\1\47\1\23\1\50\1\51\4\47"+
    "\1\55\1\56\2\47\1\54\1\47\1\31\1\32\1\47"+
    "\1\33\1\47\1\57\2\47\1\60\1\61\1\62\1\47"+
    "\1\63\4\47\1\64\3\47\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\56\1\47\1\22\1\47\1\23\1\50"+
    "\1\51\1\47\1\52\2\47\1\53\1\47\1\65\1\47"+
    "\1\66\1\47\1\31\1\32\1\47\1\33\21\47\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\47\1\22"+
    "\1\47\1\23\1\50\1\51\1\47\1\52\2\47\1\55"+
    "\1\47\1\65\1\47\1\66\1\47\1\31\1\32\1\47"+
    "\1\33\21\47\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\47\1\22\1\47\1\23\1\50\1\51\1\47"+
    "\1\67\2\47\1\53\2\47\1\70\1\54\1\47\1\31"+
    "\1\32\1\71\1\33\1\47\20\70\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\47\1\22\1\47\1\23"+
    "\1\50\1\51\1\47\1\67\2\47\1\55\2\47\1\70"+
    "\1\54\1\47\1\31\1\32\1\71\1\33\1\47\20\70"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\47"+
    "\1\22\1\47\1\23\1\50\1\51\1\47\1\72\2\47"+
    "\1\53\3\47\1\54\1\47\1\31\1\32\1\47\1\33"+
    "\21\47\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\47\1\22\1\47\1\23\1\50\1\51\1\47\1\72"+
    "\2\47\1\55\3\47\1\54\1\47\1\31\1\32\1\47"+
    "\1\33\21\47\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\47\1\22\1\47\1\23\1\50\1\51\1\47"+
    "\1\72\2\47\1\73\1\47\1\74\1\47\1\74\1\47"+
    "\1\31\1\32\1\75\1\33\21\47\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\47\1\22\1\47\1\23"+
    "\1\50\1\51\1\47\1\72\2\47\1\76\1\47\1\74"+
    "\1\47\1\74\1\47\1\31\1\32\1\75\1\33\21\47"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\77"+
    "\3\100\1\77\1\101\1\77\1\102\2\77\1\53\2\77"+
    "\4\100\2\77\1\33\1\103\20\100\10\77\3\100\1\77"+
    "\1\101\1\77\1\102\2\77\1\104\2\77\4\100\2\77"+
    "\1\33\1\103\20\100\7\77\55\0\1\105\1\106\1\0"+
    "\1\107\50\0\1\110\53\0\1\107\2\0\1\107\47\0"+
    "\5\111\1\112\1\113\45\111\7\0\1\26\44\0\7\27"+
    "\2\0\43\27\3\0\1\114\12\0\1\115\1\114\55\0"+
    "\1\116\77\0\1\117\54\0\1\120\6\0\1\121\1\106"+
    "\1\0\1\122\50\0\1\122\2\0\1\122\61\0\1\123"+
    "\2\0\1\124\7\0\20\124\34\0\1\125\35\0\1\52"+
    "\56\0\1\53\53\0\1\55\2\0\1\124\7\0\20\124"+
    "\35\0\1\126\57\0\1\127\64\0\1\130\35\0\1\131"+
    "\63\0\1\132\62\0\1\133\10\0\1\65\1\0\1\65"+
    "\11\0\3\65\5\0\20\65\10\0\1\65\1\0\1\66"+
    "\11\0\1\65\1\134\1\66\5\0\20\65\16\0\1\67"+
    "\45\0\1\135\1\0\1\135\11\0\3\135\5\0\20\135"+
    "\21\0\1\73\42\0\1\74\1\0\1\74\11\0\3\74"+
    "\5\0\20\74\21\0\1\76\2\0\1\124\7\0\20\124"+
    "\10\0\3\100\11\0\4\100\4\0\20\100\16\0\1\136"+
    "\56\0\1\104\1\0\1\137\1\124\1\137\6\0\20\124"+
    "\10\0\1\140\1\106\1\0\1\141\50\0\1\106\53\0"+
    "\1\141\2\0\1\141\50\0\1\110\1\142\51\0\7\111"+
    "\2\0\43\111\1\0\1\143\1\106\1\0\1\144\50\0"+
    "\1\144\2\0\1\144\50\0\1\145\1\0\1\145\11\0"+
    "\3\145\5\0\20\145\50\0\1\146\41\0\1\147\63\0"+
    "\1\150\45\0\1\151\53\0\1\152\60\0\1\153\50\0"+
    "\1\56\21\0\1\137\1\0\1\137\11\0\3\137\5\0"+
    "\20\137\10\0\1\154\1\106\1\0\1\155\50\0\1\155"+
    "\2\0\1\155\50\0\1\142\53\0\1\156\1\106\1\0"+
    "\1\157\50\0\1\157\2\0\1\157\76\0\1\160\54\0"+
    "\1\161\62\0\1\162\47\0\1\163\53\0\1\164\55\0"+
    "\1\165\17\0\1\166\1\106\1\167\53\0\1\167\51\0"+
    "\1\166\1\106\1\170\53\0\1\170\102\0\1\171\52\0"+
    "\1\172\54\0\1\173\62\0\1\174\45\0\1\175\21\0"+
    "\1\166\1\106\52\0\1\176\2\0\1\176\50\0\1\177"+
    "\2\0\1\177\102\0\1\200\60\0\1\201\43\0\1\202"+
    "\24\0\1\203\2\0\1\203\50\0\1\204\2\0\1\204"+
    "\76\0\1\205\55\0\1\206\25\0\1\207\53\0\1\210"+
    "\111\0\1\211\13\0\1\212\2\0\1\212\50\0\1\213"+
    "\2\0\1\213\111\0\1\214\12\0\1\215\2\0\1\215"+
    "\50\0\1\216\2\0\1\216\47\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4576];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\20\0\1\11\7\1\1\11\1\1\1\11\2\1\5\11"+
    "\4\1\1\11\6\1\1\11\12\1\2\11\2\1\1\11"+
    "\1\1\1\11\3\1\1\11\3\1\1\0\1\1\1\0"+
    "\1\11\2\0\1\1\3\11\1\1\12\0\5\1\1\0"+
    "\2\1\1\0\1\1\6\0\1\1\1\0\1\1\5\0"+
    "\1\11\1\0\1\1\3\0\1\11\1\0\1\11\3\0"+
    "\1\11\5\0\1\11\5\0\3\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[142];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  public _BeancountLexer() {
    this((java.io.Reader)null);
  }

  private final LinkedList<Integer> states = new LinkedList();

  private void yypushstate(int state) {
      states.addFirst(yystate());
        yylogstate(state);
  }

    private void yypopstate() {
      if(states.isEmpty()) {
        yylogstate(YYINITIAL);
      } else  {
        final int state = states.removeFirst();
        yylogstate(state);
      }
    }
    private void yylogstate(int state) {
//    System.out.println("   state is now "+ state);
    yybegin(state);
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _BeancountLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    int size = 0;
    for (int i = 0, length = packed.length(); i < length; i += 2) {
      size += packed.charAt(i);
    }
    char[] map = new char[size];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < packed.length()) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL.charAt(zzMarkedPosL-1)) {
        case '\n':
        case '\u000B':  // fall though
        case '\u000C':  // fall though
        case '\u0085':  // fall though
        case '\u2028':  // fall though
        case '\u2029':  // fall though
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL.charAt(zzMarkedPosL) != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL.charAt(zzMarkedPosL) != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + ZZ_CMAP(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return SKIP;
            } 
            // fall through
          case 48: break;
          case 2: 
            { return NUMBER;
            } 
            // fall through
          case 49: break;
          case 3: 
            { return MINUS;
            } 
            // fall through
          case 50: break;
          case 4: 
            { return EOL;
            } 
            // fall through
          case 51: break;
          case 5: 
            { return COMMENT;
            } 
            // fall through
          case 52: break;
          case 6: 
            { return DIVIDE;
            } 
            // fall through
          case 53: break;
          case 7: 
            { return AT;
            } 
            // fall through
          case 54: break;
          case 8: 
            { return HASH;
            } 
            // fall through
          case 55: break;
          case 9: 
            { return LCURL;
            } 
            // fall through
          case 56: break;
          case 10: 
            { return RCURL;
            } 
            // fall through
          case 57: break;
          case 11: 
            { return COMMA;
            } 
            // fall through
          case 58: break;
          case 12: 
            { return LPAREN;
            } 
            // fall through
          case 59: break;
          case 13: 
            { return RPAREN;
            } 
            // fall through
          case 60: break;
          case 14: 
            { return PLUS;
            } 
            // fall through
          case 61: break;
          case 15: 
            { return ASTERISK;
            } 
            // fall through
          case 62: break;
          case 16: 
            { return BAD_CHARACTER;
            } 
            // fall through
          case 63: break;
          case 17: 
            { yylogstate(YYINITIAL); return EOL;
            } 
            // fall through
          case 64: break;
          case 18: 
            { return WHITE_SPACE;
            } 
            // fall through
          case 65: break;
          case 19: 
            { yylogstate(sTXN); return TXN;
            } 
            // fall through
          case 66: break;
          case 20: 
            { yypushstate(sACCOUNT); return ACCOUNT_WORD;
            } 
            // fall through
          case 67: break;
          case 21: 
            { yypopstate(); return EOL;
            } 
            // fall through
          case 68: break;
          case 22: 
            { return META_KV_DELIMITER;
            } 
            // fall through
          case 69: break;
          case 23: 
            { yypushback(yylength()); yypopstate();
            } 
            // fall through
          case 70: break;
          case 24: 
            { yypopstate(); return WHITE_SPACE;
            } 
            // fall through
          case 71: break;
          case 25: 
            { return ACCOUNT_WORD;
            } 
            // fall through
          case 72: break;
          case 26: 
            { return COLON;
            } 
            // fall through
          case 73: break;
          case 27: 
            { /*this effectively detects the last posting line*/ yypushback(yylength()); yypopstate();
            } 
            // fall through
          case 74: break;
          case 28: 
            { return TAG_LINK_VALUE;
            } 
            // fall through
          case 75: break;
          case 29: 
            { return CARET;
            } 
            // fall through
          case 76: break;
          case 30: 
            { return NEGATIVE_NUMBER;
            } 
            // fall through
          case 77: break;
          case 31: 
            { return STRING;
            } 
            // fall through
          case 78: break;
          case 32: 
            { return CURRENCY;
            } 
            // fall through
          case 79: break;
          case 33: 
            { return ATAT;
            } 
            // fall through
          case 80: break;
          case 34: 
            { return LCURLCURL;
            } 
            // fall through
          case 81: break;
          case 35: 
            { return RCURLCURL;
            } 
            // fall through
          case 82: break;
          case 36: 
            { return META_KEY;
            } 
            // fall through
          case 83: break;
          case 37: 
            { yypopstate();  return EOL;
            } 
            // fall through
          case 84: break;
          case 38: 
            { yypushback(nonWsIndex(yytext())); yypushstate(sPOSTING); yypushstate(sACCOUNT); return INDENT;
            } 
            // fall through
          case 85: break;
          case 39: 
            { yypushback(nonWsIndex(yytext())); yypushstate(sMETA_LIST); return INDENT;
            } 
            // fall through
          case 86: break;
          case 40: 
            { yylogstate(sOPEN); return OPEN;
            } 
            // fall through
          case 87: break;
          case 41: 
            { yylogstate(sPRICE); return PRICE;
            } 
            // fall through
          case 88: break;
          case 42: 
            { yylogstate(sEVENT); return EVENT;
            } 
            // fall through
          case 89: break;
          case 43: 
            { yylogstate(sOPT); return OPTION;
            } 
            // fall through
          case 90: break;
          case 44: 
            { yylogstate(sBALANCE); return BALANCE;
            } 
            // fall through
          case 91: break;
          case 45: 
            { yylogstate(sCOMMODITY); return COMMODITY;
            } 
            // fall through
          case 92: break;
          case 46: 
            { return DATE;
            } 
            // fall through
          case 93: break;
          case 47: 
            { yylogstate(sDATE_ENTRY); return DATE;
            } 
            // fall through
          case 94: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
